import os

with open("src/lib/services/communities.ts", "a", encoding="utf-8") as f:
    f.write("\n\n// Update community details (Admin only)\n")
    f.write("export const updateCommunity = async (communityId: string, updates: Partial<Community>) => {\n")
    f.write("  try {\n")
    f.write("    const communityRef = doc(db, 'communities', communityId);\n")
    f.write("    await updateDoc(communityRef, updates);\n")
    f.write("    return { success: true };\n")
    f.write("  } catch (error: any) {\n")
    f.write("    console.error('Error updating community:', error);\n")
    f.write("    return { success: false, error: error.message };\n")
    f.write("  }\n")
    f.write("};\n")
    
    f.write("\n// Delete community (Admin only)\n")
    f.write("export const deleteCommunity = async (communityId: string) => {\n")
    f.write("  try {\n")
    f.write("    const communityRef = doc(db, 'communities', communityId);\n")
    f.write("    await deleteDoc(communityRef);\n")
    f.write("    return { success: true };\n")
    f.write("  } catch (error: any) {\n")
    f.write("    console.error('Error deleting community:', error);\n")
    f.write("    return { success: false, error: error.message };\n")
    f.write("  }\n")
    f.write("};\n")
